name: Check new upstream commits

on:
  push:
  repository_dispatch:
    types: [check_upstream]

jobs:
  check_upstream_commits:
    runs-on: ubuntu-latest
    name: Check upstream latest commits

    steps:
    - name: Checkout main
      uses: actions/checkout@v2

    - name: Fetch upstream changes
      id: sync
      uses: ivanmilov/upstream_check_new_commits@v1
      with:
        upstream_repository: huntresslabs/deployment-scripts
        upstream_branch: master
        target_branch: master_upstream
        
    - name: Send Test Email Notification
      if: github.event_name == 'repository_dispatch' && github.event.action == 'check_upstream'
      uses: dawidd6/action-send-mail@v3.9.0
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.ALERTS_EMAIL_USERNAME }}
        password: ${{ secrets.ALERTS_EMAIL_PASSWORD }}
        subject: Test Alert from ${{ github.repository }}
        body: 'This is a test alert email sent from the GitHub Actions workflow.'
        to: sketchum@hummingbird.tech
        from: alerts@myspringpoint.com
