name: Test Email

on:
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  send_test_email:
    runs-on: ubuntu-latest
    name: Send Test Email Notification

    steps:
    - name: Send Test Email Notification
      uses: dawidd6/action-send-mail@v3.9.0
      with:
        server_address: smtp.office365.com
        server_port: 587
        username: ${{ secrets.ALERTS_EMAIL_USERNAME }}
        password: ${{ secrets.ALERTS_EMAIL_PASSWORD }}
        subject: Test Alert from ${{ github.repository }}
        body: 'This is a test alert email sent from the GitHub Actions workflow.'
        to: sketchum@hummingbird.tech
        from: alerts@myspringpoint.com
